#!/bin/bash

echo "🎉 Panic on Error Extension Setup Complete!"
echo ""
echo "📁 Project Structure:"
tree -L 2 -I 'node_modules|out' 2>/dev/null || find . -maxdepth 2 -not -path '*/node_modules/*' -not -path '*/out/*' | head -20
echo ""
echo "✅ Extension compiled successfully!"
echo "✅ Sound file ready: sounds/fah.mp3"
echo ""
echo "🚀 How to test:"
echo "1. Press F5 in VS Code to launch Extension Development Host"
echo "2. Open any file from playground/ folder"
echo "3. Uncomment error lines to trigger the sound!"
echo ""
echo "🎮 Commands:"
echo "- Ctrl+Shift+P → 'Panic on Error: Toggle Sound'"
echo ""
echo "🔧 Playground files:"
echo "- playground/test.js (JavaScript errors)"
echo "- playground/test.ts (TypeScript errors)"
echo "- playground/test.py (Python errors)"
